### ISSUE TITLE
on culture page, "benefits" not aligned properly 

### ISSUE THREAD

**Issue by MCarter89** [Skookum/skookum.com#26]
**Observed In**
iPad Air OS 8.4

When navigating to the cultures page, "benefits" on the left hand side is right aligned and runs into the bullet points. see screenshot: 

![benefits](https://cloud.githubusercontent.com/assets/6033234/8596495/bd1e188c-261d-11e5-8cb6-3013ae810790.PNG)

**Comment by chrishowie** [comment]
Also on this page on larger browsers Looks as though an image is shown as a placeholder instead of actual content on larger displays. 

![benefits ipad mini](https://cloud.githubusercontent.com/assets/8906955/8621219/698b7dba-26f2-11e5-9f1b-c3fd77c75624.PNG)

On iOS/Android the Benefits is just shown in Orange 

![galaxy tab 10 horizontal orange](https://cloud.githubusercontent.com/assets/8906955/8621261/b06b6bc8-26f2-11e5-8455-4d584c3566ee.png)
